import MathCert.Domains.UnionClosed.LatticeDeletion
import MathCert.Domains.UnionClosed.LatticeInterval
import MathCert.Domains.UnionClosed.LatticeSubposet
import Mathlib.Data.Fintype.Option
import Mathlib.Data.Fintype.Sum

/-!
# Minimum lattice counterexamples

This file formalizes the finite-lattice form of Frankl's conjecture used by
Bouchard and proves the first selected minimum-counterexample condition.
-/

namespace MathCert.UnionClosed.Lattice

open Finset Set

universe u

variable {L : Type u} [Fintype L] [Lattice L] [BoundedOrder L]

/-- Cardinality of the principal upper cone generated by `j`. -/
noncomputable def upperConeCard (j : L) : Nat :=
  @Fintype.card {x : L // j ≤ x} (Fintype.ofFinite _)

/-- Number of members of `s` lying in the principal upper cone of `j`. -/
noncomputable def upperConeInterCard (j : L) (s : Finset L) : Nat := by
  classical
  exact (s.filter fun x => j ≤ x).card

/--
A finite lattice counterexample to the lattice formulation of Frankl:
every sup-irreducible element lies below strictly more than half the lattice.
-/
def IsCounterexample (L : Type u) [Fintype L] [Lattice L] [BoundedOrder L] : Prop :=
  1 < Fintype.card L ∧
    ∀ j : L, SupIrred j → Fintype.card L < 2 * upperConeCard j

/-- Minimum cardinality among finite lattice counterexamples in the same universe. -/
def IsMinimumCounterexample
    (L : Type u) [Fintype L] [Lattice L] [BoundedOrder L] : Prop :=
  IsCounterexample L ∧
    ∀ (K : Type u) [Fintype K] [Lattice K] [BoundedOrder K],
      IsCounterexample K → Fintype.card L ≤ Fintype.card K

omit [Fintype L] in
theorem supIrred_of_isAtom {a : L} (ha : IsAtom a) : SupIrred a := by
  constructor
  · exact ha.bot_lt.not_isMin
  · intro b c hbc
    have hb : b ≤ a := by rw [← hbc]; exact le_sup_left
    have hc : c ≤ a := by rw [← hbc]; exact le_sup_right
    rcases (ha.le_iff.mp hb) with rfl | rfl
    · right
      simpa [ha.ne_bot] using hbc
    · exact Or.inl rfl

omit [Fintype L] in
theorem infIrred_of_isCoatom {a : L} (ha : IsCoatom a) : InfIrred a := by
  constructor
  · exact ha.lt_top.not_isMax
  · intro b c hbc
    have hab : a ≤ b := by
      rw [← hbc]
      exact inf_le_left
    rcases ha.le_iff.mp hab with rfl | rfl
    · right
      simpa using hbc
    · exact Or.inl rfl

theorem upperConeCard_top : upperConeCard (⊤ : L) = 1 := by
  let e : {x : L // (⊤ : L) ≤ x} ≃ PUnit.{u + 1} :=
    { toFun := fun _ => PUnit.unit
      invFun := fun _ => ⟨⊤, le_rfl⟩
      left_inv := fun x => by
        apply Subtype.ext
        exact (top_unique x.2).symm
      right_inv := fun _ => rfl }
  letI : Fintype {x : L // (⊤ : L) ≤ x} := Fintype.ofFinite _
  exact (Fintype.card_congr e).trans Fintype.card_punit

omit [BoundedOrder L] in
theorem upperConeCard_lt_of_lt {a b : L} (hab : a < b) :
    upperConeCard b < upperConeCard a := by
  letI : Fintype {x : L // b ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : L // a ≤ x} := Fintype.ofFinite _
  unfold upperConeCard
  let f : {x : L // b ≤ x} → {x : L // a ≤ x} :=
    fun x => ⟨x.1, hab.le.trans x.2⟩
  apply Fintype.card_lt_of_injective_of_notMem
    (b := (⟨a, le_rfl⟩ : {x : L // a ≤ x})) f
  · intro x y hxy
    apply Subtype.ext
    exact congrArg (fun z => z.1) hxy
  · intro h
    obtain ⟨z, hz⟩ := h
    have hza := congrArg Subtype.val hz
    change z.1 = a at hza
    exact (not_le_of_gt hab) (z.2.trans_eq hza)

private theorem upperConeCard_embedded_add_one
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (e : K ↪o L)
    (hno : ¬EmbeddedSubposet.HasBoundaryTouch e)
    {d : L} (hd : IsCoatom d) (hdle : d ≤ e (⊤ : K))
    {q : K} (hq_bot : q ≠ ⊥) (hq_top : q ≠ ⊤) :
    upperConeCard (e q) ≤ upperConeCard q + 1 := by
  classical
  letI : Fintype {x : L // e q ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : K // q ≤ x} := Fintype.ofFinite _
  unfold upperConeCard
  let f : {x : L // e q ≤ x} → Option {x : K // q ≤ x} := fun x =>
    if hx : ∃ k : K, e k = x.1 then
      let k := Classical.choose hx
      some
        ⟨k, by
          have hk := Classical.choose_spec hx
          exact e.le_iff_le.mp (by rw [hk]; exact x.2)⟩
    else
      none
  have hf : Function.Injective f := by
    intro x y hxy
    by_cases hx : ∃ k : K, e k = x.1
    · by_cases hy : ∃ k : K, e k = y.1
      · have hxspec := Classical.choose_spec hx
        have hyspec := Classical.choose_spec hy
        have hsub :
            (⟨Classical.choose hx, by
              have hk := Classical.choose_spec hx
              exact e.le_iff_le.mp (by rw [hk]; exact x.2)⟩ :
                {x : K // q ≤ x}) =
              ⟨Classical.choose hy, by
                have hk := Classical.choose_spec hy
                exact e.le_iff_le.mp (by rw [hk]; exact y.2)⟩ := by
          exact Option.some.inj (by simpa [f, hx, hy] using hxy)
        have hk :
            Classical.choose hx = Classical.choose hy :=
          congrArg Subtype.val hsub
        apply Subtype.ext
        calc
          x.1 = e (Classical.choose hx) := hxspec.symm
          _ = e (Classical.choose hy) := by rw [hk]
          _ = y.1 := hyspec
      · have hfalse : False := by
          simpa [f, hx, hy] using hxy
        exact hfalse.elim
    · by_cases hy : ∃ k : K, e k = y.1
      · have hfalse : False := by
          simpa [f, hx, hy] using hxy
        exact hfalse.elim
      · have hxtop :
            x.1 = ⊤ :=
          EmbeddedSubposet.outside_upperCone_eq_top_of_noBoundary
            hno hd hdle hq_bot hq_top x.2
            (by
              intro hmem
              exact hx ((EmbeddedSubposet.mem_carrier (e := e)).1 hmem))
        have hytop :
            y.1 = ⊤ :=
          EmbeddedSubposet.outside_upperCone_eq_top_of_noBoundary
            hno hd hdle hq_bot hq_top y.2
            (by
              intro hmem
              exact hy ((EmbeddedSubposet.mem_carrier (e := e)).1 hmem))
        apply Subtype.ext
        rw [hxtop, hytop]
  have hcard := Fintype.card_le_of_injective f hf
  simpa using hcard

private theorem deletedTop_supIrred_to_original
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (hTopSup : SupIrred (⊤ : K))
    [Fintype (Deleted (⊤ : K))] [Nonempty (Deleted (⊤ : K))]
    [BoundedOrder (Deleted (⊤ : K))]
    (q : Deleted (⊤ : K))
    (hq :
      letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
      SupIrred q) :
    SupIrred q.1 := by
  classical
  letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
  have hq' : SupIrred q := hq
  constructor
  · intro hmin
    apply hq'.not_isMin
    intro z hz
    exact hmin hz
  · intro a b hab
    by_cases ha : a = q.1
    · exact Or.inl ha
    by_cases hb : b = q.1
    · exact Or.inr hb
    have ha_le : a ≤ q.1 := by
      rw [← hab]
      exact le_sup_left
    have hb_le : b ≤ q.1 := by
      rw [← hab]
      exact le_sup_right
    have ha_ne_top : a ≠ ⊤ := by
      intro hatop
      have htop_le_q : (⊤ : K) ≤ q.1 := by simpa [hatop] using ha_le
      exact q.2 (top_unique htop_le_q)
    have hb_ne_top : b ≠ ⊤ := by
      intro hbtop
      have htop_le_q : (⊤ : K) ≤ q.1 := by simpa [hbtop] using hb_le
      exact q.2 (top_unique htop_le_q)
    let a' : Deleted (⊤ : K) := ⟨a, ha_ne_top⟩
    let b' : Deleted (⊤ : K) := ⟨b, hb_ne_top⟩
    have hjoin : a' ⊔ b' = q := by
      apply Subtype.ext
      change (deletedSup hTopSup a' b').1 = q.1
      simp [deletedSup, a', b', hab]
    rcases hq'.2 hjoin with hqa | hqb
    · have hval := congrArg Subtype.val hqa
      exact Or.inl hval
    · have hval := congrArg Subtype.val hqb
      exact Or.inr hval

private theorem upperConeCard_deletedTop_add_one
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (hTopSup : SupIrred (⊤ : K))
    [Fintype (Deleted (⊤ : K))] [Nonempty (Deleted (⊤ : K))]
    [BoundedOrder (Deleted (⊤ : K))]
    (q : Deleted (⊤ : K)) :
    letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
    upperConeCard q.1 ≤ upperConeCard q + 1 := by
  classical
  letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
  letI : Fintype {x : K // q.1 ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : Deleted (⊤ : K) // q ≤ x} := Fintype.ofFinite _
  unfold upperConeCard
  let f : {x : K // q.1 ≤ x} →
      Option {x : Deleted (⊤ : K) // q ≤ x} := fun x =>
    if hx : x.1 = ⊤ then none
    else some ⟨⟨x.1, hx⟩, x.2⟩
  have hf : Function.Injective f := by
    intro x y hxy
    by_cases hx : x.1 = ⊤
    · by_cases hy : y.1 = ⊤
      · apply Subtype.ext
        rw [hx, hy]
      · have hfalse : False := by
          simpa [f, hx, hy] using hxy.symm
        exact hfalse.elim
    · by_cases hy : y.1 = ⊤
      · have hfalse : False := by
          simpa [f, hx, hy] using hxy
        exact hfalse.elim
      · have hsub :
            (⟨⟨x.1, hx⟩, x.2⟩ :
              {x : Deleted (⊤ : K) // q ≤ x}) =
            ⟨⟨y.1, hy⟩, y.2⟩ := by
          exact Option.some.inj (by simpa [f, hx, hy] using hxy)
        apply Subtype.ext
        exact congrArg (fun z : {x : Deleted (⊤ : K) // q ≤ x} => z.1.1) hsub
  have hcard := Fintype.card_le_of_injective f hf
  simpa using hcard

private theorem upperConeCard_embedded_deletedTop_add_two
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (e : K ↪o L)
    (hTopSup : SupIrred (⊤ : K))
    [Fintype (Deleted (⊤ : K))] [Nonempty (Deleted (⊤ : K))]
    [BoundedOrder (Deleted (⊤ : K))]
    (hno : ¬EmbeddedSubposet.HasBoundaryTouch e)
    {d : L} (hd : IsCoatom d) (hdle : d ≤ e (⊤ : K))
    (q : Deleted (⊤ : K)) (hq_bot : q.1 ≠ ⊥) :
    letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
    upperConeCard (e q.1) ≤ upperConeCard q + 2 := by
  classical
  letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
  have hamb :
      upperConeCard (e q.1) ≤ upperConeCard q.1 + 1 :=
    upperConeCard_embedded_add_one e hno hd hdle hq_bot q.2
  have hdel :
      upperConeCard q.1 ≤ upperConeCard q + 1 :=
    upperConeCard_deletedTop_add_one hTopSup q
  omega

theorem uniqueAtom_le_of_ne_bot {a x : L}
    (hunique : ∀ b : L, IsAtom b → b = a)
    (hx : x ≠ ⊥) :
    a ≤ x := by
  obtain hbot | ⟨b, hb, hbx⟩ := eq_bot_or_exists_atom_le x
  · exact (hx hbot).elim
  · simpa [hunique b hb] using hbx

private theorem upperConeCard_le_deleted
    {m r : L}
    (hm : InfIrred m)
    [Fintype (Deleted m)] [BoundedOrder (Deleted m)]
    (q : Deleted m)
    (hrm : ¬ r ≤ m)
    (hqr : q.1 ≤ r) :
    letI : Lattice (Deleted m) := deletedInfIrredLattice hm
    upperConeCard r ≤ upperConeCard q := by
  letI : Lattice (Deleted m) := deletedInfIrredLattice hm
  letI : Fintype {x : L // r ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : Deleted m // q ≤ x} := Fintype.ofFinite _
  unfold upperConeCard
  apply Fintype.card_le_of_injective
    (fun x : {x : L // r ≤ x} =>
      (⟨⟨x.1, by
        intro hxm
        exact hrm (x.2.trans_eq hxm)⟩, hqr.trans x.2⟩ :
        {x : Deleted m // q ≤ x}))
  intro x y hxy
  apply Subtype.ext
  exact congrArg (fun z => z.1.1) hxy

private theorem upperConeCard_le_deleted_add_one
    {m : L}
    (hm : InfIrred m)
    [Fintype (Deleted m)] [BoundedOrder (Deleted m)]
    (q : Deleted m)
    (hquc : q.1 ≤ upperCover m) :
    letI : Lattice (Deleted m) := deletedInfIrredLattice hm
    upperConeCard m ≤ upperConeCard q + 1 := by
  classical
  letI : Lattice (Deleted m) := deletedInfIrredLattice hm
  letI : Fintype {x : L // m ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : Deleted m // q ≤ x} := Fintype.ofFinite _
  unfold upperConeCard
  rw [← Fintype.card_option]
  apply Fintype.card_le_of_injective
    (fun x : {x : L // m ≤ x} =>
      if hxm : x.1 = m then
        none
      else
        some
          (⟨⟨x.1, hxm⟩,
            hquc.trans
              (upperCover_le_of_lt (lt_of_le_of_ne x.2 (Ne.symm hxm)))⟩ :
            {x : Deleted m // q ≤ x}))
  intro x y hxy
  by_cases hxm : x.1 = m
  · have hym : y.1 = m := by
      by_contra hym
      simp [hxm, hym] at hxy
    apply Subtype.ext
    exact hxm.trans hym.symm
  · have hym : y.1 ≠ m := by
      intro hym
      simp [hxm, hym] at hxy
    simp only [hxm, hym, ↓reduceDIte, Option.some.injEq] at hxy
    apply Subtype.ext
    exact congrArg (fun z => z.1.1) hxy

private theorem upperConeCard_le_deleted_add_one_of_le
    {m r : L}
    (hm : InfIrred m)
    [Fintype (Deleted m)] [BoundedOrder (Deleted m)]
    (q : Deleted m)
    (hqr : q.1 ≤ r) :
    letI : Lattice (Deleted m) := deletedInfIrredLattice hm
    upperConeCard r ≤ upperConeCard q + 1 := by
  classical
  letI : Lattice (Deleted m) := deletedInfIrredLattice hm
  letI : Fintype {x : L // r ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : Deleted m // q ≤ x} := Fintype.ofFinite _
  unfold upperConeCard
  rw [← Fintype.card_option]
  apply Fintype.card_le_of_injective
    (fun x : {x : L // r ≤ x} =>
      if hxm : x.1 = m then
        none
      else
        some
          (⟨⟨x.1, hxm⟩, hqr.trans x.2⟩ :
            {x : Deleted m // q ≤ x}))
  intro x y hxy
  by_cases hxm : x.1 = m
  · have hym : y.1 = m := by
      by_contra hym
      simp [hxm, hym] at hxy
    apply Subtype.ext
    exact hxm.trans hym.symm
  · have hym : y.1 ≠ m := by
      intro hym
      simp [hxm, hym] at hxy
    simp only [hxm, hym, ↓reduceDIte, Option.some.injEq] at hxy
    apply Subtype.ext
    exact congrArg (fun z => z.1.1) hxy

private theorem deleted_supIrred_of_incomparable
    {x y : L}
    (hxInf : InfIrred x)
    (hySup : SupIrred y)
    (hxy : ¬x ≤ y) :
    letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
    SupIrred (⟨y, by rintro rfl; exact hxy le_rfl⟩ : Deleted x) := by
  letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
  have hy_ne_x : y ≠ x := by
    rintro rfl
    exact hxy le_rfl
  let y' : Deleted x := ⟨y, hy_ne_x⟩
  constructor
  · obtain ⟨z, hz⟩ := not_isMin_iff.mp hySup.1
    apply not_isMin_iff.mpr
    exact ⟨⟨z, fun hzx => hxy (by simpa [hzx] using hz.le)⟩, hz⟩
  · intro b c hbc
    change deletedSupOfInfIrred hxInf b c = y' at hbc
    by_cases hs : b.1 ⊔ c.1 = x
    · have hucy : upperCover x = y := by
        have hval := congrArg Subtype.val hbc
        change (deletedSupOfInfIrred hxInf b c).1 = y at hval
        simpa [deletedSupOfInfIrred, hs] using hval
      exact (hxy ((lt_upperCover hxInf).le.trans_eq hucy)).elim
    · have hold : b.1 ⊔ c.1 = y := by
        have hval := congrArg Subtype.val hbc
        change (deletedSupOfInfIrred hxInf b c).1 = y at hval
        simpa [deletedSupOfInfIrred, hs] using hval
      rcases hySup.2 hold with hb | hc
      · left
        exact Subtype.ext hb
      · right
        exact Subtype.ext hc

private theorem deleted_infIrred_of_incomparable
    {x y : L}
    (hxInf : InfIrred x)
    (hyInf : InfIrred y)
    (hyx : ¬y ≤ x) :
    letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
    InfIrred (⟨y, by rintro rfl; exact hyx le_rfl⟩ : Deleted x) := by
  letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
  have hy_ne_x : y ≠ x := by
    rintro rfl
    exact hyx le_rfl
  let y' : Deleted x := ⟨y, hy_ne_x⟩
  constructor
  · obtain ⟨z, hz⟩ := not_isMax_iff.mp hyInf.1
    apply not_isMax_iff.mpr
    exact ⟨⟨z, fun hzx => hyx (by simpa [hzx] using hz.le)⟩, hz⟩
  · intro b c hbc
    change deletedInfOfInfIrred hxInf b c = y' at hbc
    have hold : b.1 ⊓ c.1 = y := by
      have hval := congrArg Subtype.val hbc
      simpa [deletedInfOfInfIrred] using hval
    rcases hyInf.2 hold with hb | hc
    · left
      exact Subtype.ext hb
    · right
      exact Subtype.ext hc

private theorem deleted_supIrred_is_supIrred
    {a : L} (ha : IsAtom a)
    (hunique : ∀ b : L, IsAtom b → b = a)
    (j : Deleted a)
    (hj : letI := deletedSupIrredLattice (supIrred_of_isAtom ha); SupIrred j) :
    SupIrred j.1 := by
  letI : Lattice (Deleted a) := deletedSupIrredLattice (supIrred_of_isAtom ha)
  have hj' : SupIrred j := hj
  have hj_not_min : ¬IsMin j.1 := by
    obtain ⟨z, hz⟩ := not_isMin_iff.mp hj'.1
    exact not_isMin_iff.mpr ⟨z.1, hz⟩
  have hj_ne_bot : j.1 ≠ ⊥ := by
    intro h
    apply hj_not_min
    rw [h]
    exact isMin_bot
  constructor
  · exact hj_not_min
  · intro b c hbc
    by_cases hb : b = a
    · subst b
      have hc_ne_bot : c ≠ ⊥ := by
        intro hc
        apply j.2
        simpa [hc] using hbc.symm
      have hac := uniqueAtom_le_of_ne_bot hunique hc_ne_bot
      right
      simpa [sup_eq_right.mpr hac] using hbc
    · by_cases hc : c = a
      · subst c
        have hb_ne_bot : b ≠ ⊥ := by
          intro hb0
          apply j.2
          simpa [hb0] using hbc.symm
        have hab := uniqueAtom_le_of_ne_bot hunique hb_ne_bot
        left
        simpa [sup_eq_left.mpr hab] using hbc
      · have hdeleted :
            (⟨b, hb⟩ ⊔ ⟨c, hc⟩ : Deleted a) = j := by
          apply Subtype.ext
          exact hbc
        rcases hj'.2 hdeleted with hbj | hcj
        · left
          exact congrArg Subtype.val hbj
        · right
          exact congrArg Subtype.val hcj

private noncomputable def deletedUpperConeEquiv
    {a : L} (ha : IsAtom a)
    (hunique : ∀ b : L, IsAtom b → b = a)
    (j : Deleted a)
    (hj : letI := deletedSupIrredLattice (supIrred_of_isAtom ha); SupIrred j) :
    {x : Deleted a // j ≤ x} ≃ {x : L // j.1 ≤ x} := by
  letI : Lattice (Deleted a) := deletedSupIrredLattice (supIrred_of_isAtom ha)
  have hjL := deleted_supIrred_is_supIrred ha hunique j hj
  have hj_ne_bot := hjL.ne_bot
  have hj_not_le_atom : ¬j.1 ≤ a := by
    intro hja
    rcases ha.le_iff.mp hja with hjbot | hja'
    · exact hj_ne_bot hjbot
    · exact j.2 hja'
  exact
    { toFun := fun x => ⟨x.1.1, x.2⟩
      invFun := fun x =>
        ⟨⟨x.1, by
          intro hxa
          apply hj_not_le_atom
          simpa [hxa] using x.2⟩, x.2⟩
      left_inv := fun x => by rfl
      right_inv := fun x => by rfl }

private theorem deleted_isCounterexample
    {a : L} (hC : IsCounterexample L)
    (ha : IsAtom a)
    (hunique : ∀ b : L, IsAtom b → b = a) :
    letI : Lattice (Deleted a) := deletedSupIrredLattice (supIrred_of_isAtom ha)
    letI : Fintype (Deleted a) := Fintype.ofFinite _
    letI : Nonempty (Deleted a) := ⟨⟨⊥, ha.ne_bot.symm⟩⟩
    letI : BoundedOrder (Deleted a) := Fintype.toBoundedOrder _
    IsCounterexample (Deleted a) := by
  letI : Lattice (Deleted a) := deletedSupIrredLattice (supIrred_of_isAtom ha)
  letI : Fintype (Deleted a) := Fintype.ofFinite _
  letI : Nonempty (Deleted a) := ⟨⟨⊥, ha.ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted a) := Fintype.toBoundedOrder _
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hC.1
  letI : Nontrivial L := hL_nontrivial
  have ha_ne_top : a ≠ ⊤ := by
    have hcard := hC.1
    intro hatop
    have hfreq := hC.2 a (supIrred_of_isAtom ha)
    subst a
    rw [upperConeCard_top] at hfreq
    omega
  have hdeleted_nontrivial : Nontrivial (Deleted a) := by
    refine ⟨⟨⟨⊥, ha.ne_bot.symm⟩, ⟨⊤, ha_ne_top.symm⟩, ?_⟩⟩
    intro h
    exact bot_ne_top (congrArg Subtype.val h)
  constructor
  · exact Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
  · intro j hj
    have hjL := deleted_supIrred_is_supIrred ha hunique j hj
    have hcard_lt :
        Fintype.card (Deleted a) < Fintype.card L :=
      Fintype.card_subtype_lt (p := fun x : L => x ≠ a) (x := a) (by simp)
    have hcone :
        upperConeCard j = upperConeCard j.1 := by
      unfold upperConeCard
      letI : Fintype {x : Deleted a // j ≤ x} := Fintype.ofFinite _
      letI : Fintype {x : L // j.1 ≤ x} := Fintype.ofFinite _
      exact Fintype.card_congr (deletedUpperConeEquiv ha hunique j hj)
    rw [hcone]
    exact hcard_lt.trans (hC.2 j.1 hjL)

private theorem deleted_supIrred_eq_upperCover
    {m : L} (hm : InfIrred m)
    (q : Deleted m)
    (hq : letI := deletedInfIrredLattice hm; SupIrred q)
    (hqL : ¬SupIrred q.1) :
    q.1 = upperCover m := by
  letI : Lattice (Deleted m) := deletedInfIrredLattice hm
  have hq' : SupIrred q := hq
  have hq_not_min : ¬IsMin q.1 := by
    obtain ⟨z, hz⟩ := not_isMin_iff.mp hq'.1
    exact not_isMin_iff.mpr ⟨z.1, hz⟩
  rw [not_supIrred] at hqL
  rcases hqL with hmin | ⟨b, c, hbc, hb, hc⟩
  · exact (hq_not_min hmin).elim
  have hmissing : b = m ∨ c = m := by
    by_contra h
    push Not at h
    have hdeleted :
        deletedSupOfInfIrred hm ⟨b, h.1⟩ ⟨c, h.2⟩ = q := by
      apply Subtype.ext
      rw [deletedSupOfInfIrred, dif_neg]
      · exact hbc
      · intro hbm
        exact q.2 (hbc ▸ hbm)
    rcases hq'.2 hdeleted with hbq | hcq
    · exact (ne_of_lt hb) (congrArg Subtype.val hbq)
    · exact (ne_of_lt hc) (congrArg Subtype.val hcq)
  obtain ⟨d, hd_ne, hmd, hdq⟩ :
      ∃ d : L, d ≠ m ∧ m ⊔ d = q.1 ∧ d < q.1 := by
    rcases hmissing with rfl | rfl
    · refine ⟨c, ?_, hbc, hc⟩
      intro hcm
      exact q.2 (by simpa [hcm] using hbc.symm)
    · refine ⟨b, ?_, ?_, hb⟩
      · intro hbm
        exact q.2 (by simpa [hbm] using hbc.symm)
      · simpa [sup_comm] using hbc
  have hmq : m < q.1 := lt_of_le_of_ne
    (by rw [← hmd]; exact le_sup_left) (Ne.symm q.2)
  have hucq : upperCover m ≤ q.1 := upperCover_le_of_lt hmq
  have hsup : upperCover m ⊔ d = q.1 := by
    apply le_antisymm
    · exact sup_le hucq hdq.le
    · rw [← hmd]
      exact sup_le_sup_right (le_upperCover m) d
  have huc_ne : upperCover m ≠ m := ne_of_gt (lt_upperCover hm)
  have hdeleted :
      deletedSupOfInfIrred hm ⟨upperCover m, huc_ne⟩ ⟨d, hd_ne⟩ = q := by
    apply Subtype.ext
    rw [deletedSupOfInfIrred, dif_neg]
    · exact hsup
    · intro h
      exact (not_le_of_gt (lt_upperCover hm)) (le_sup_left.trans h.le)
  rcases hq'.2 hdeleted with huc | hd
  · exact (congrArg Subtype.val huc).symm
  · exact ((ne_of_lt hdq) (congrArg Subtype.val hd)).elim

private theorem deleted_infIrred_isCounterexample
    {m j : L}
    (hC : IsCounterexample L)
    (hm : InfIrred m)
    (hm_ne_bot : m ≠ ⊥)
    (hj : SupIrred j)
    (hmj : m < j) :
    letI : Lattice (Deleted m) := deletedInfIrredLattice hm
    letI : Fintype (Deleted m) := Fintype.ofFinite _
    letI : Nonempty (Deleted m) := ⟨⟨⊥, hm_ne_bot.symm⟩⟩
    letI : BoundedOrder (Deleted m) := Fintype.toBoundedOrder _
    IsCounterexample (Deleted m) := by
  letI : Lattice (Deleted m) := deletedInfIrredLattice hm
  letI : Fintype (Deleted m) := Fintype.ofFinite _
  letI : Nonempty (Deleted m) := ⟨⟨⊥, hm_ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted m) := Fintype.toBoundedOrder _
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hC.1
  letI : Nontrivial L := hL_nontrivial
  have hdeleted_nontrivial : Nontrivial (Deleted m) := by
    refine ⟨⟨⟨⊥, hm_ne_bot.symm⟩, ⟨⊤, hm.ne_top.symm⟩, ?_⟩⟩
    intro h
    exact bot_ne_top (congrArg Subtype.val h)
  constructor
  · exact Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
  · intro q hq
    have hcard_lt :
        Fintype.card (Deleted m) < Fintype.card L :=
      Fintype.card_subtype_lt (p := fun x : L => x ≠ m) (x := m) (by simp)
    by_cases hqL : SupIrred q.1
    · by_cases hqm : q.1 < m
      · have hcone :=
          upperConeCard_le_deleted hm q (not_le_of_gt hmj)
            (hqm.le.trans hmj.le)
        exact hcard_lt.trans ((hC.2 j hj).trans_le (Nat.mul_le_mul_left 2 hcone))
      · have hq_not_le_m : ¬q.1 ≤ m := by
          intro hle
          rcases lt_or_eq_of_le hle with hlt | heq
          · exact hqm hlt
          · exact q.2 heq
        have hcone :=
          upperConeCard_le_deleted hm q hq_not_le_m le_rfl
        exact hcard_lt.trans ((hC.2 q.1 hqL).trans_le (Nat.mul_le_mul_left 2 hcone))
    · have hquc := deleted_supIrred_eq_upperCover hm q hq hqL
      have hcone :=
        upperConeCard_le_deleted hm q (not_le_of_gt hmj)
          (by rw [hquc]; exact upperCover_le_of_lt hmj)
      exact hcard_lt.trans ((hC.2 j hj).trans_le (Nat.mul_le_mul_left 2 hcone))

private theorem deleted_doublyIrred_isCounterexample
    {x : L}
    (hC : IsCounterexample L)
    (hxSup : SupIrred x)
    (hxInf : InfIrred x)
    (hconeStrong : Fintype.card L + 1 < 2 * upperConeCard x) :
    letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
    letI : Fintype (Deleted x) := Fintype.ofFinite _
    letI : Nonempty (Deleted x) := ⟨⟨⊥, hxSup.ne_bot.symm⟩⟩
    letI : BoundedOrder (Deleted x) := Fintype.toBoundedOrder _
    IsCounterexample (Deleted x) := by
  letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
  letI : Fintype (Deleted x) := Fintype.ofFinite _
  letI : Nonempty (Deleted x) := ⟨⟨⊥, hxSup.ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted x) := Fintype.toBoundedOrder _
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hC.1
  letI : Nontrivial L := hL_nontrivial
  have hcard_two : 1 < Fintype.card L := hC.1
  have hdeleted_nontrivial : Nontrivial (Deleted x) := by
    refine ⟨⟨⟨⊥, hxSup.ne_bot.symm⟩, ⟨⊤, hxInf.ne_top.symm⟩, ?_⟩⟩
    intro h
    exact bot_ne_top (congrArg Subtype.val h)
  have hcard_deleted :
      Fintype.card (Deleted x) = Fintype.card L - 1 := by
    simp only [Fintype.card_subtype_compl, Fintype.card_subtype_eq]
  constructor
  · exact Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
  · intro q hq
    by_cases hqL : SupIrred q.1
    · by_cases hqx : q.1 < x
      · have hcone :=
          upperConeCard_le_deleted_add_one hxInf q
            (hqx.le.trans (le_upperCover x))
        omega
      · have hq_not_le_x : ¬q.1 ≤ x := by
          intro hle
          rcases lt_or_eq_of_le hle with hlt | heq
          · exact hqx hlt
          · exact q.2 heq
        have hcone :=
          upperConeCard_le_deleted hxInf q hq_not_le_x le_rfl
        have hcounter := hC.2 q.1 hqL
        omega
    · have hquc := deleted_supIrred_eq_upperCover hxInf q hq hqL
      have hcone :=
        upperConeCard_le_deleted_add_one hxInf q (by rw [hquc])
      omega

/--
UC-WP05-L001, Bouchard Corollary 2.2:
a minimum-cardinality finite-lattice counterexample has at least two atoms.
-/
theorem minimumCounterexample_has_two_atoms
    (hmin : IsMinimumCounterexample L) :
    ∃ a b : L, IsAtom a ∧ IsAtom b ∧ a ≠ b := by
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hmin.1.1
  letI : Nontrivial L := hL_nontrivial
  obtain ⟨a, ha⟩ := IsAtomic.exists_atom (α := L)
  by_contra htwo
  have hunique : ∀ b : L, IsAtom b → b = a := by
    intro b hb
    by_contra hba
    exact htwo ⟨a, b, ha, hb, Ne.symm hba⟩
  letI : Lattice (Deleted a) := deletedSupIrredLattice (supIrred_of_isAtom ha)
  letI : Fintype (Deleted a) := Fintype.ofFinite _
  letI : Nonempty (Deleted a) := ⟨⟨⊥, ha.ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted a) := Fintype.toBoundedOrder _
  have hdeleted := deleted_isCounterexample hmin.1 ha hunique
  have hminimal := hmin.2 (Deleted a) hdeleted
  have hsmaller :
      Fintype.card (Deleted a) < Fintype.card L :=
    Fintype.card_subtype_lt (p := fun x : L => x ≠ a) (x := a) (by simp)
  exact (not_le_of_gt hsmaller) hminimal

/--
UC-WP05-L004, Bouchard Theorem 2.3:
in a minimum counterexample, no inf-irreducible element lies strictly below a
sup-irreducible element.
-/
theorem minimumCounterexample_no_infIrred_lt_supIrred
    (hmin : IsMinimumCounterexample L) :
    ∀ m j : L, InfIrred m → SupIrred j → ¬ m < j := by
  intro m j hm hj hmj
  obtain ⟨a, b, ha, hb, hab⟩ := minimumCounterexample_has_two_atoms hmin
  have hm_ne_bot : m ≠ ⊥ := by
    intro hmbot
    have habinf : a ⊓ b = m := by
      rw [hmbot]
      exact (ha.disjoint_of_ne hb hab).eq_bot
    rcases hm.2 habinf with ham | hbm
    · exact ha.ne_bot (ham.trans hmbot)
    · exact hb.ne_bot (hbm.trans hmbot)
  letI : Lattice (Deleted m) := deletedInfIrredLattice hm
  letI : Fintype (Deleted m) := Fintype.ofFinite _
  letI : Nonempty (Deleted m) := ⟨⟨⊥, hm_ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted m) := Fintype.toBoundedOrder _
  have hdeleted := deleted_infIrred_isCounterexample hmin.1 hm hm_ne_bot hj hmj
  have hminimal := hmin.2 (Deleted m) hdeleted
  have hsmaller :
      Fintype.card (Deleted m) < Fintype.card L :=
    Fintype.card_subtype_lt (p := fun x : L => x ≠ m) (x := m) (by simp)
  exact (not_le_of_gt hsmaller) hminimal

/--
UC-WP05-L005, Bouchard Corollary 2.4:
the top element of a minimum counterexample is join-reducible.
-/
theorem minimumCounterexample_top_join_reducible
    (hmin : IsMinimumCounterexample L) :
    ∃ b c : L, b ⊔ c = ⊤ ∧ b < ⊤ ∧ c < ⊤ := by
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hmin.1.1
  letI : Nontrivial L := hL_nontrivial
  obtain ⟨m, hm⟩ := IsCoatomic.exists_coatom (α := L)
  have htop : ¬SupIrred (⊤ : L) := by
    intro htop
    exact minimumCounterexample_no_infIrred_lt_supIrred hmin m ⊤
      (infIrred_of_isCoatom hm) htop hm.lt_top
  exact (not_supIrred.mp htop).resolve_left not_isMin_top

/--
UC-WP05-L006, Bouchard Lemma 2.5:
a doubly irreducible element in a minimum counterexample has an upper cone of
exactly half the successor of the lattice cardinality.
-/
theorem minimumCounterexample_doublyIrred_upperCone
    (hmin : IsMinimumCounterexample L)
    {x : L} (hxSup : SupIrred x) (hxInf : InfIrred x) :
    2 * upperConeCard x = Fintype.card L + 1 := by
  have hlower : Fintype.card L + 1 ≤ 2 * upperConeCard x := by
    have hcounter := hmin.1.2 x hxSup
    omega
  apply le_antisymm
  · by_contra hupper
    have hconeStrong : Fintype.card L + 1 < 2 * upperConeCard x := by
      omega
    letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
    letI : Fintype (Deleted x) := Fintype.ofFinite _
    letI : Nonempty (Deleted x) := ⟨⟨⊥, hxSup.ne_bot.symm⟩⟩
    letI : BoundedOrder (Deleted x) := Fintype.toBoundedOrder _
    have hdeleted :=
      deleted_doublyIrred_isCounterexample hmin.1 hxSup hxInf hconeStrong
    have hminimal := hmin.2 (Deleted x) hdeleted
    have hsmaller :
        Fintype.card (Deleted x) < Fintype.card L :=
      Fintype.card_subtype_lt (p := fun y : L => y ≠ x) (x := x) (by simp)
    exact (not_le_of_gt hsmaller) hminimal
  · exact hlower

/--
UC-WP05-L007, Bouchard Theorem 2.6:
a minimum counterexample has at most one doubly irreducible element.
-/
theorem minimumCounterexample_doublyIrred_unique
    (hmin : IsMinimumCounterexample L) :
    ∀ x y : L,
      SupIrred x → InfIrred x → SupIrred y → InfIrred y → x = y := by
  intro x y hxSup hxInf hySup hyInf
  by_contra hxy_ne
  have hnot_xy_lt : ¬x < y :=
    minimumCounterexample_no_infIrred_lt_supIrred hmin x y hxInf hySup
  have hnot_yx_lt : ¬y < x :=
    minimumCounterexample_no_infIrred_lt_supIrred hmin y x hyInf hxSup
  have hnot_xy_le : ¬x ≤ y := by
    intro hxy
    exact hnot_xy_lt (lt_of_le_of_ne hxy hxy_ne)
  have hnot_yx_le : ¬y ≤ x := by
    intro hyx
    exact hnot_yx_lt (lt_of_le_of_ne hyx (Ne.symm hxy_ne))
  have hy_ne_x : y ≠ x := Ne.symm hxy_ne
  letI : Lattice (Deleted x) := deletedInfIrredLattice hxInf
  letI : Fintype (Deleted x) := Fintype.ofFinite _
  letI : Nonempty (Deleted x) := ⟨⟨⊥, hxSup.ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted x) := Fintype.toBoundedOrder _
  let y' : Deleted x := ⟨y, hy_ne_x⟩
  have hySup' : SupIrred y' :=
    deleted_supIrred_of_incomparable hxInf hySup hnot_xy_le
  have hyInf' : InfIrred y' :=
    deleted_infIrred_of_incomparable hxInf hyInf hnot_yx_le
  letI : Lattice (Deleted y') := deletedInfIrredLattice hyInf'
  letI : Fintype (Deleted y') := Fintype.ofFinite _
  letI : Nonempty (Deleted y') :=
    ⟨⟨⟨⊥, hxSup.ne_bot.symm⟩, by
      intro h
      exact hySup.ne_bot (congrArg Subtype.val h).symm⟩⟩
  letI : BoundedOrder (Deleted y') := Fintype.toBoundedOrder _
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hmin.1.1
  letI : Nontrivial L := hL_nontrivial
  have hdeleted_nontrivial : Nontrivial (Deleted y') := by
    refine ⟨⟨
      ⟨⟨⊥, hxSup.ne_bot.symm⟩, by
        intro h
        exact hySup.ne_bot (congrArg Subtype.val h).symm⟩,
      ⟨⟨⊤, hxInf.ne_top.symm⟩, by
        intro h
        exact hyInf.ne_top (congrArg Subtype.val h).symm⟩,
      ?_⟩⟩
    intro h
    exact bot_ne_top (congrArg (fun z => z.1.1) h)
  have hcard_first :
      Fintype.card (Deleted x) = Fintype.card L - 1 := by
    simp only [Fintype.card_subtype_compl, Fintype.card_subtype_eq]
  have hcard_second :
      Fintype.card (Deleted y') = Fintype.card (Deleted x) - 1 := by
    simp only [Fintype.card_subtype_compl, Fintype.card_subtype_eq]
  have hcard_two_deleted :
      Fintype.card (Deleted y') + 2 = Fintype.card L := by
    have hnonempty_card : 2 ≤ Fintype.card (Deleted y') :=
      Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
    omega
  have hdeleted : IsCounterexample (Deleted y') := by
    constructor
    · exact Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
    · intro q hq
      by_cases hqFirst : SupIrred q.1
      · by_cases hqL : SupIrred q.1.1
        · by_cases hqx : q.1.1 < x
          · have hstrict := upperConeCard_lt_of_lt hqx
            have hxCone :=
              minimumCounterexample_doublyIrred_upperCone hmin hxSup hxInf
            have hconeFirst :=
              upperConeCard_le_deleted_add_one_of_le hxInf q.1 le_rfl
            have hconeSecond :=
              upperConeCard_le_deleted_add_one_of_le hyInf' q le_rfl
            omega
          · by_cases hqy : q.1.1 < y
            · have hstrict := upperConeCard_lt_of_lt hqy
              have hyCone :=
                minimumCounterexample_doublyIrred_upperCone hmin hySup hyInf
              have hconeFirst :=
                upperConeCard_le_deleted_add_one_of_le hxInf q.1 le_rfl
              have hconeSecond :=
                upperConeCard_le_deleted_add_one_of_le hyInf' q le_rfl
              omega
            · have hq_not_le_x : ¬q.1.1 ≤ x := by
                intro hle
                rcases lt_or_eq_of_le hle with hlt | heq
                · exact hqx hlt
                · exact q.1.2 heq
              have hq_not_le_y : ¬q.1 ≤ y' := by
                intro hle
                have hleL : q.1.1 ≤ y := hle
                rcases lt_or_eq_of_le hleL with hlt | heq
                · exact hqy hlt
                · exact q.2 (Subtype.ext heq)
              have hconeFirst :=
                upperConeCard_le_deleted hxInf q.1 hq_not_le_x le_rfl
              have hconeSecond :=
                upperConeCard_le_deleted hyInf' q hq_not_le_y le_rfl
              have hcounter := hmin.1.2 q.1.1 hqL
              omega
        · have hquc :=
            deleted_supIrred_eq_upperCover hxInf q.1 hqFirst hqL
          have hconeFirst :=
            upperConeCard_le_deleted_add_one hxInf q.1 (by rw [hquc])
          have hq_not_le_y : ¬q.1 ≤ y' := by
            intro hle
            apply hnot_xy_le
            have hqle : q.1.1 ≤ y := hle
            rw [hquc] at hqle
            exact (le_upperCover x).trans hqle
          have hconeSecond :=
            upperConeCard_le_deleted hyInf' q hq_not_le_y le_rfl
          have hxCone :=
            minimumCounterexample_doublyIrred_upperCone hmin hxSup hxInf
          omega
      · have hquc :=
          deleted_supIrred_eq_upperCover hyInf' q hq hqFirst
        have hconeFirst :=
          upperConeCard_le_deleted hxInf y' hnot_yx_le le_rfl
        have hconeSecond :=
          upperConeCard_le_deleted_add_one hyInf' q (by rw [hquc])
        have hyCone :=
          minimumCounterexample_doublyIrred_upperCone hmin hySup hyInf
        omega
  have hminimal := hmin.2 (Deleted y') hdeleted
  have hsmaller : Fintype.card (Deleted y') < Fintype.card L := by
    omega
  exact (not_le_of_gt hsmaller) hminimal

private noncomputable def deletedFinsetUpperConeEquiv
    {s : Finset L} (hs : ∀ a ∈ s, InfIrred a)
    {j : L} {q : DeletedFinset s}
    (hjq : deletedFinsetCeilOfInfIrred hs j = q) :
    letI : Lattice (DeletedFinset s) := deletedFinsetInfIrredLattice hs
    {x : DeletedFinset s // q ≤ x} ≃
      {x : L // j ≤ x ∧ x ∉ s} := by
  letI : Lattice (DeletedFinset s) := deletedFinsetInfIrredLattice hs
  exact
    { toFun := fun x =>
        ⟨x.1.1,
          ⟨(le_deletedFinsetCeilOfInfIrred hs j).trans
              (by simpa [hjq] using x.2),
            x.1.2⟩⟩
      invFun := fun x =>
        ⟨⟨x.1, x.2.2⟩, by
          rw [← hjq]
          exact deletedFinsetCeilOfInfIrred_le hs x.2.2 x.2.1⟩
      left_inv := fun x => by rfl
      right_inv := fun x => by rfl }

private theorem upperConeCard_deletedFinset_add_removed
    {s : Finset L} (hs : ∀ a ∈ s, InfIrred a)
    [Fintype (DeletedFinset s)]
    {j : L} {q : DeletedFinset s}
    (hjq : deletedFinsetCeilOfInfIrred hs j = q) :
    letI : Lattice (DeletedFinset s) := deletedFinsetInfIrredLattice hs
    upperConeCard q + upperConeInterCard j s = upperConeCard j := by
  classical
  letI : Lattice (DeletedFinset s) := deletedFinsetInfIrredLattice hs
  unfold upperConeInterCard
  unfold upperConeCard
  letI : Fintype {x : DeletedFinset s // q ≤ x} := Fintype.ofFinite _
  letI : Fintype {x : L // j ≤ x ∧ x ∉ s} := Fintype.ofFinite _
  letI : Fintype {x : L // j ≤ x} := Fintype.ofFinite _
  rw [Fintype.card_congr (deletedFinsetUpperConeEquiv hs hjq)]
  rw [Fintype.card_subtype, Fintype.card_subtype]
  let t := Finset.univ.filter fun x : L => j ≤ x
  have hsurv :
      Finset.univ.filter (fun x : L => j ≤ x ∧ x ∉ s) = t \ s := by
    ext x
    simp [t]
  have hremoved :
      s.filter (fun x => j ≤ x) = t ∩ s := by
    ext x
    simp [t, and_comm]
  rw [hsurv, hremoved]
  exact Finset.card_sdiff_add_card_inter t s

/--
UC-WP05-L009, Bouchard Theorem 2.9:
every nonempty finite set of inf-irreducible elements in a minimum
counterexample has a strict-majority upper cone generated by some
sup-irreducible element.
-/
theorem minimumCounterexample_meetIrred_majority
    (hmin : IsMinimumCounterexample L)
    (M : Finset L) (hM : M.Nonempty)
    (hMirred : ∀ m ∈ M, InfIrred m) :
    ∃ j : L,
      SupIrred j ∧ M.card < 2 * upperConeInterCard j M := by
  classical
  by_contra hmajority
  push Not at hmajority
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hmin.1.1
  letI : Nontrivial L := hL_nontrivial
  obtain ⟨a, _, ha, _, _⟩ := minimumCounterexample_has_two_atoms hmin
  have hbot : (⊥ : L) ∉ M := by
    intro hbotM
    exact minimumCounterexample_no_infIrred_lt_supIrred hmin ⊥ a
      (hMirred _ hbotM) (supIrred_of_isAtom ha) ha.bot_lt
  have htop : (⊤ : L) ∉ M := by
    intro htopM
    exact (hMirred _ htopM).ne_top rfl
  letI : Lattice (DeletedFinset M) := deletedFinsetInfIrredLattice hMirred
  letI : Nonempty (DeletedFinset M) := ⟨⟨⊤, htop⟩⟩
  letI : BoundedOrder (DeletedFinset M) := Fintype.toBoundedOrder _
  have hdeleted_nontrivial : Nontrivial (DeletedFinset M) := by
    refine ⟨⟨⟨⊥, hbot⟩, ⟨⊤, htop⟩, ?_⟩⟩
    intro h
    exact bot_ne_top (congrArg Subtype.val h)
  have hcard_deleted :
      Fintype.card (DeletedFinset M) = Fintype.card L - M.card := by
    calc
      Fintype.card (DeletedFinset M) =
          Fintype.card L - Fintype.card {x : L // x ∈ M} :=
        Fintype.card_subtype_compl (fun x : L => x ∈ M)
      _ = Fintype.card L - M.card := by rw [Fintype.card_coe]
  have hMcard_le : M.card ≤ Fintype.card L := by
    simpa using Finset.card_le_univ M
  have hdeleted : IsCounterexample (DeletedFinset M) := by
    constructor
    · exact Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
    · intro q hq
      obtain ⟨j, hj, hjq⟩ :=
        deletedFinset_supIrred_has_origin hMirred q hq
      have hcone :=
        upperConeCard_deletedFinset_add_removed hMirred hjq
      have hcounter := hmin.1.2 j hj
      have hremoved := hmajority j hj
      omega
  have hminimal := hmin.2 (DeletedFinset M) hdeleted
  have hMcard_pos : 0 < M.card := Finset.card_pos.mpr hM
  omega

/-- The finite set of all inf-irreducible elements of `L`. -/
noncomputable def infIrredFinset : Finset L := by
  classical
  exact Finset.univ.filter InfIrred

/--
UC-WP05-L010, Bouchard Corollary 2.10:
some sup-irreducible element lies below strictly more than half of all
inf-irreducible elements in a minimum counterexample.
-/
theorem minimumCounterexample_allMeetIrred_majority
    (hmin : IsMinimumCounterexample L) :
    ∃ j : L,
      SupIrred j ∧
        (infIrredFinset (L := L)).card <
          2 * upperConeInterCard j (infIrredFinset (L := L)) := by
  classical
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hmin.1.1
  letI : Nontrivial L := hL_nontrivial
  obtain ⟨m, hm⟩ := IsCoatomic.exists_coatom (α := L)
  apply minimumCounterexample_meetIrred_majority hmin
  · exact ⟨m, by simp [infIrredFinset, infIrred_of_isCoatom hm]⟩
  · intro x hx
    simpa [infIrredFinset] using hx

/--
UC-WP05-L011, Bouchard Corollary 2.11:
any two inf-irreducible elements in a minimum counterexample have a common
sup-irreducible lower bound.
-/
theorem minimumCounterexample_twoMeetIrred_common_lower
    (hmin : IsMinimumCounterexample L)
    {m₁ m₂ : L} (hm₁ : InfIrred m₁) (hm₂ : InfIrred m₂) :
    ∃ j : L, SupIrred j ∧ j ≤ m₁ ∧ j ≤ m₂ := by
  classical
  obtain ⟨j, hj, hmajority⟩ :=
    minimumCounterexample_meetIrred_majority hmin {m₁, m₂}
      (by simp)
      (by
        intro m hm
        simp only [Finset.mem_insert, Finset.mem_singleton] at hm
        rcases hm with rfl | rfl
        · exact hm₁
        · exact hm₂)
  refine ⟨j, hj, ?_, ?_⟩
  · by_contra hjm₁
    by_cases hjm₂ : j ≤ m₂
    · have hmne : m₁ ≠ m₂ := by
        intro h
        apply hjm₁
        simpa [h] using hjm₂
      have hpair : ({m₁, m₂} : Finset L).card = 2 :=
        Finset.card_pair hmne
      have hfilter :
          (({m₁, m₂} : Finset L).filter fun m => j ≤ m).card ≤ 1 := by
        calc
          (({m₁, m₂} : Finset L).filter fun m => j ≤ m).card ≤
              ({m₂} : Finset L).card := by
            apply Finset.card_mono
            intro x hx
            simp only [Finset.mem_filter, Finset.mem_insert,
              Finset.mem_singleton] at hx
            rcases hx.1 with rfl | rfl
            · exact (hjm₁ hx.2).elim
            · simp
          _ = 1 := Finset.card_singleton m₂
      unfold upperConeInterCard at hmajority
      omega
    · have hfilter :
          (({m₁, m₂} : Finset L).filter fun m => j ≤ m).card = 0 := by
        rw [Finset.card_eq_zero, Finset.filter_eq_empty_iff]
        intro x hx
        simp only [Finset.mem_insert, Finset.mem_singleton] at hx
        rcases hx with rfl | rfl
        · exact hjm₁
        · exact hjm₂
      have hpair_pos : 0 < ({m₁, m₂} : Finset L).card := by simp
      unfold upperConeInterCard at hmajority
      omega
  · by_contra hjm₂
    by_cases hjm₁ : j ≤ m₁
    · have hmne : m₁ ≠ m₂ := by
        intro h
        apply hjm₂
        simpa [h] using hjm₁
      have hpair : ({m₁, m₂} : Finset L).card = 2 :=
        Finset.card_pair hmne
      have hfilter :
          (({m₁, m₂} : Finset L).filter fun m => j ≤ m).card ≤ 1 := by
        calc
          (({m₁, m₂} : Finset L).filter fun m => j ≤ m).card ≤
              ({m₁} : Finset L).card := by
            apply Finset.card_mono
            intro x hx
            simp only [Finset.mem_filter, Finset.mem_insert,
              Finset.mem_singleton] at hx
            rcases hx.1 with rfl | rfl
            · simp
            · exact (hjm₂ hx.2).elim
          _ = 1 := Finset.card_singleton m₁
      unfold upperConeInterCard at hmajority
      omega
    · have hfilter :
          (({m₁, m₂} : Finset L).filter fun m => j ≤ m).card = 0 := by
        rw [Finset.card_eq_zero, Finset.filter_eq_empty_iff]
        intro x hx
        simp only [Finset.mem_insert, Finset.mem_singleton] at hx
        rcases hx with rfl | rfl
        · exact hjm₁
        · exact hjm₂
      have hpair_pos : 0 < ({m₁, m₂} : Finset L).card := by simp
      unfold upperConeInterCard at hmajority
      omega

/--
UC-WP05-L012, Bouchard Theorem 2.12:
every inf-irreducible element in a minimum counterexample lies above a
sup-irreducible element whose upper cone has the minimum possible strict
majority size.
-/
theorem minimumCounterexample_meetIrred_has_exactCone_lower
    (hmin : IsMinimumCounterexample L)
    {m : L} (hm : InfIrred m) :
    ∃ j : L,
      SupIrred j ∧ j ≤ m ∧
        2 * upperConeCard j = Fintype.card L + 1 := by
  classical
  by_contra hexact
  have hstrong :
      ∀ j : L, SupIrred j → j ≤ m →
        Fintype.card L + 1 < 2 * upperConeCard j := by
    intro j hj hjm
    have hcounter := hmin.1.2 j hj
    by_contra hnot
    have heq :
        2 * upperConeCard j = Fintype.card L + 1 := by
      omega
    exact hexact ⟨j, hj, hjm, heq⟩
  have hL_nontrivial : Nontrivial L :=
    Fintype.one_lt_card_iff_nontrivial.mp hmin.1.1
  letI : Nontrivial L := hL_nontrivial
  obtain ⟨a, _, ha, _, _⟩ := minimumCounterexample_has_two_atoms hmin
  have hm_ne_bot : m ≠ ⊥ := by
    intro hmbot
    exact minimumCounterexample_no_infIrred_lt_supIrred hmin m a hm
      (supIrred_of_isAtom ha) (by simpa [hmbot] using ha.bot_lt)
  have hs : ∀ x ∈ ({m} : Finset L), InfIrred x := by
    intro x hx
    have hxm : x = m := Finset.mem_singleton.mp hx
    subst x
    exact hm
  have hbot : (⊥ : L) ∉ ({m} : Finset L) := by
    simpa [Finset.mem_singleton] using Ne.symm hm_ne_bot
  have htop : (⊤ : L) ∉ ({m} : Finset L) := by
    simpa [Finset.mem_singleton] using Ne.symm hm.ne_top
  letI : Lattice (DeletedFinset ({m} : Finset L)) :=
    deletedFinsetInfIrredLattice hs
  letI : Nonempty (DeletedFinset ({m} : Finset L)) := ⟨⟨⊤, htop⟩⟩
  letI : BoundedOrder (DeletedFinset ({m} : Finset L)) :=
    Fintype.toBoundedOrder _
  have hdeleted_nontrivial :
      Nontrivial (DeletedFinset ({m} : Finset L)) := by
    refine ⟨⟨⟨⊥, hbot⟩, ⟨⊤, htop⟩, ?_⟩⟩
    intro h
    exact bot_ne_top (congrArg Subtype.val h)
  have hcard_deleted :
      Fintype.card (DeletedFinset ({m} : Finset L)) =
        Fintype.card L - 1 := by
    calc
      Fintype.card (DeletedFinset ({m} : Finset L)) =
          Fintype.card L -
            Fintype.card {x : L // x ∈ ({m} : Finset L)} :=
        Fintype.card_subtype_compl (fun x : L => x ∈ ({m} : Finset L))
      _ = Fintype.card L - 1 := by
        rw [Fintype.card_coe, Finset.card_singleton]
  have hdeleted :
      IsCounterexample (DeletedFinset ({m} : Finset L)) := by
    constructor
    · exact Fintype.one_lt_card_iff_nontrivial.mpr hdeleted_nontrivial
    · intro q hq
      obtain ⟨j, hj, hjq⟩ :=
        deletedFinset_supIrred_has_origin hs q hq
      have hcone :=
        upperConeCard_deletedFinset_add_removed hs hjq
      by_cases hjm : j ≤ m
      · have hinter : upperConeInterCard j ({m} : Finset L) = 1 := by
          unfold upperConeInterCard
          rw [Finset.filter_singleton]
          simp [hjm]
        have hjstrong := hstrong j hj hjm
        rw [hinter] at hcone
        have hcone' :
            upperConeCard q + 1 = upperConeCard j := hcone
        have hqbound :
            Fintype.card L ≤ 2 * upperConeCard q := by
          omega
        have hcard_pos : 0 < Fintype.card L :=
          Nat.zero_lt_of_lt hmin.1.1
        have hcard_drop :
            Fintype.card L - 1 < Fintype.card L :=
          Nat.sub_lt hcard_pos (by decide)
        rw [hcard_deleted]
        exact hcard_drop.trans_le hqbound
      · have hinter : upperConeInterCard j ({m} : Finset L) = 0 := by
          unfold upperConeInterCard
          rw [Finset.filter_singleton]
          simp [hjm]
        have hjcounter := hmin.1.2 j hj
        rw [hinter] at hcone
        have hcone' :
            upperConeCard q = upperConeCard j := by
          simpa using hcone
        rw [← hcone'] at hjcounter
        rw [hcard_deleted]
        exact (Nat.sub_le _ _).trans_lt hjcounter
  have hminimal :=
    hmin.2 (DeletedFinset ({m} : Finset L)) hdeleted
  have hsmaller :
      Fintype.card (DeletedFinset ({m} : Finset L)) <
        Fintype.card L := by
    exact
      Fintype.card_subtype_lt
        (p := fun x : L => x ∉ ({m} : Finset L))
        (x := m) (by simp)
  exact (not_le_of_gt hsmaller) hminimal

private theorem upperConeCard_upperInterval
    {x : L} [Fintype (Set.Ici x)] (q : Set.Ici x) :
    upperConeCard q = upperConeCard q.1 := by
  unfold upperConeCard
  letI : Fintype {z : Set.Ici x // q ≤ z} := Fintype.ofFinite _
  letI : Fintype {z : L // q.1 ≤ z} := Fintype.ofFinite _
  exact Fintype.card_congr (upperIntervalUpperConeEquiv x q)

private theorem upperConeCard_upperCover_add_one
    {c : L} (hc : InfIrred c) :
    upperConeCard (upperCover c) + 1 = upperConeCard c := by
  classical
  let e :
      {z : L // c ≤ z} ≃ Option {z : L // upperCover c ≤ z} := by
    refine
      { toFun := fun z =>
          if h : z.1 = c then none
          else some ⟨z.1, upperCover_le_of_lt (lt_of_le_of_ne z.2 (Ne.symm h))⟩
        invFun := fun z =>
          match z with
          | none => ⟨c, le_rfl⟩
          | some z => ⟨z.1, (le_upperCover c).trans z.2⟩
        left_inv := ?_
        right_inv := ?_ }
    · intro z
      by_cases h : z.1 = c
      · apply Subtype.ext
        simp [h]
      · apply Subtype.ext
        simp [h]
    · intro z
      cases z with
      | none => simp
      | some z =>
          have hne : z.1 ≠ c := by
            intro h
            have hlt := lt_upperCover hc
            exact (not_le_of_gt hlt) (by simpa [h] using z.2)
          simp [hne]
  unfold upperConeCard
  letI : Fintype {z : L // c ≤ z} := Fintype.ofFinite _
  letI : Fintype {z : L // upperCover c ≤ z} := Fintype.ofFinite _
  have hcard := Fintype.card_congr e
  simpa [Nat.add_comm] using hcard.symm

private theorem upperIntervalCard_add_outside
    (x : L) :
    upperIntervalCard x + outsideUpperIntervalCard x =
      Fintype.card L := by
  classical
  let e : L ≃ Sum (Set.Ici x) {y : L // ¬x ≤ y} := by
    refine
      { toFun := fun y =>
          if h : x ≤ y then Sum.inl ⟨y, h⟩ else Sum.inr ⟨y, h⟩
        invFun := fun y =>
          match y with
          | Sum.inl y => y.1
          | Sum.inr y => y.1
        left_inv := ?_
        right_inv := ?_ }
    · intro y
      by_cases h : x ≤ y <;> simp [h]
    · intro y
      cases y with
      | inl y =>
          change
            (if h : x ≤ y.1 then Sum.inl (⟨y.1, h⟩ : Set.Ici x)
              else Sum.inr (⟨y.1, h⟩ : {z : L // ¬x ≤ z})) =
              Sum.inl y
          split
          · rfl
          · rename_i h
            exact (h y.2).elim
      | inr y =>
          change
            (if h : x ≤ y.1 then Sum.inl (⟨y.1, h⟩ : Set.Ici x)
              else Sum.inr (⟨y.1, h⟩ : {z : L // ¬x ≤ z})) =
              Sum.inr y
          split
          · rename_i h
            exact (y.2 h).elim
          · rfl
  letI : Fintype (Set.Ici x) := Fintype.ofFinite _
  letI : Fintype {y : L // ¬x ≤ y} := Fintype.ofFinite _
  unfold upperIntervalCard outsideUpperIntervalCard
  have hcard := Fintype.card_congr e
  simpa [Fintype.card_sum] using hcard.symm

private theorem upperConeCard_closure_add_incomparable
    {x cBot : L} [Fintype (Set.Ici x)]
    (hcBot : Incomparable cBot x)
    (hleast : ∀ y : L, Incomparable y x → cBot ≤ y)
    (q : Set.Ici x) (hq : upperIntervalCeil x cBot = q) :
    upperConeCard q + incomparableCard x =
      upperConeCard cBot := by
  classical
  let e :
      {y : L // cBot ≤ y} ≃
        Sum {z : Set.Ici x // q ≤ z} {y : L // Incomparable y x} := by
    refine
      { toFun := fun y =>
          if hy : x ≤ y.1 then
            Sum.inl ⟨⟨y.1, hy⟩, ?_⟩
          else
            Sum.inr ⟨y.1, ?_⟩
        invFun := fun y =>
          match y with
          | Sum.inl y => ⟨y.1.1, ?_⟩
          | Sum.inr y => ⟨y.1, ?_⟩
        left_inv := ?_
        right_inv := ?_ }
    · rw [← hq]
      change x ⊔ cBot ≤ y.1
      exact sup_le hy y.2
    · exact
        ⟨fun hyx => hcBot.1 (y.2.trans hyx), hy⟩
    ·
      have hcq : cBot ≤ q.1 := by
        rw [← hq]
        exact le_sup_right
      exact hcq.trans y.2
    · exact hleast y.1 y.2
    · intro y
      by_cases hy : x ≤ y.1 <;> simp [hy]
    · intro y
      cases y with
      | inl y =>
          have hy : x ≤ y.1.1 := y.1.2
          simp [hy]
      | inr y =>
          have hy : ¬x ≤ y.1 := y.2.2
          simp [hy]
  letI : Fintype {y : L // cBot ≤ y} := Fintype.ofFinite _
  letI : Fintype {z : Set.Ici x // q ≤ z} := Fintype.ofFinite _
  letI : Fintype {y : L // Incomparable y x} := Fintype.ofFinite _
  unfold upperConeCard incomparableCard
  have hcard := Fintype.card_congr e
  simpa [Fintype.card_sum] using hcard.symm

/--
UC-WP05-L013, Bouchard Theorem 2.13:
for every non-endpoint element of a minimum counterexample, the elements
incomparable with it do not form a chain.
-/
theorem minimumCounterexample_incomparables_not_chain
    (hmin : IsMinimumCounterexample L)
    {x : L} (hx_bot : x ≠ ⊥) (hx_top : x ≠ ⊤) :
    ¬IsChain (· ≤ ·) (incomparableSet x) := by
  classical
  intro hchain
  letI : Fintype (Set.Ici x) := Fintype.ofFinite _
  have hcard_interval :
      Fintype.card (Set.Ici x) = upperIntervalCard x := by
    unfold upperIntervalCard
    exact Fintype.card_congr (Equiv.refl _)
  have hcard_le :
      Fintype.card (Set.Ici x) ≤ Fintype.card L :=
    Fintype.card_subtype_le _
  have hinterval_nontrivial :
      1 < Fintype.card (Set.Ici x) := by
    apply Fintype.one_lt_card_iff_nontrivial.mpr
    refine ⟨⟨⟨x, le_rfl⟩, ⟨⊤, le_top⟩, ?_⟩⟩
    intro h
    apply hx_top
    exact congrArg Subtype.val h
  let P := incomparableFinset x
  have hPmem : ∀ y : L, y ∈ P ↔ Incomparable y x := by
    intro y
    exact mem_incomparableFinset
  have hinterval : IsCounterexample (Set.Ici x) := by
    constructor
    · exact hinterval_nontrivial
    · intro q hq
      by_cases hqL : SupIrred q.1
      · have hcounter := hmin.1.2 q.1 hqL
        have hcone := upperConeCard_upperInterval q
        omega
      obtain ⟨j, hj, hjq⟩ :=
        upperInterval_supIrred_has_origin x q hq
      have hj_not_le_x : ¬j ≤ x := by
        intro hjx
        apply hq.ne_bot
        rw [← hjq]
        apply Subtype.ext
        exact sup_eq_left.mpr hjx
      have hx_not_le_j : ¬x ≤ j := by
        intro hxj
        apply hqL
        have hqj : q.1 = j := by
          rw [← hjq]
          exact sup_eq_right.mpr hxj
        simpa [hqj] using hj
      have hjinc : Incomparable j x :=
        ⟨hj_not_le_x, hx_not_le_j⟩
      have hjP : j ∈ P := (hPmem j).2 hjinc
      have hPne : P.Nonempty := ⟨j, hjP⟩
      obtain ⟨cTop, hcTopMax⟩ := P.exists_maximal hPne
      have hcTop : Incomparable cTop x :=
        (hPmem cTop).1 hcTopMax.1
      have hgreat : ∀ y : L, Incomparable y x → y ≤ cTop := by
        intro y hy
        exact chain_maximal_is_greatest hchain
          (fun z hz => (hPmem z).1 hz) hcTopMax y ((hPmem y).2 hy)
      have hcTopInf : InfIrred cTop :=
        infIrred_of_greatest_incomparable hcTop hgreat
      obtain ⟨cBot, hcBotMin⟩ := P.exists_minimal hPne
      have hcBot : Incomparable cBot x :=
        (hPmem cBot).1 hcBotMin.1
      have hleast : ∀ y : L, Incomparable y x → cBot ≤ y := by
        intro y hy
        exact chain_minimal_is_least hchain
          (fun z hz => (hPmem z).1 hz) hcBotMin y ((hPmem y).2 hy)
      have hcBotSup : SupIrred cBot :=
        supIrred_of_least_incomparable hcBot hleast
      by_cases hcTopSup : SupIrred cTop
      · have htopExact :=
          minimumCounterexample_doublyIrred_upperCone
            hmin hcTopSup hcTopInf
        have hxu : x ≤ upperCover cTop := by
          by_cases huc : Incomparable (upperCover cTop) x
          · have hle := hgreat (upperCover cTop) huc
            exact ((not_le_of_gt (lt_upperCover hcTopInf)) hle).elim
          rcases le_or_ge_of_not_incomparable huc with hle | hge
          · exact
              (hcTop.1 ((le_upperCover cTop).trans hle)).elim
          · exact hge
        have hsup_uc : x ⊔ cTop = upperCover cTop := by
          apply le_antisymm
          · exact sup_le hxu (le_upperCover cTop)
          · exact
              upperCover_le_of_lt
                (sup_lt_right_of_incomparable hcTop)
        have hq_uc : q.1 ≤ upperCover cTop := by
          rw [← hsup_uc, ← hjq]
          exact sup_le_sup_left (hgreat j hjinc) x
        have hcone_le :
            upperConeCard (upperCover cTop) ≤ upperConeCard q := by
          have hcone_interval := upperConeCard_upperInterval q
          rw [hcone_interval]
          rcases hq_uc.eq_or_lt with hEq | hlt
          · simp [hEq]
          · exact (upperConeCard_lt_of_lt hlt).le
        have hcoverCone :=
          upperConeCard_upperCover_add_one hcTopInf
        have houtside_two : 2 ≤ outsideUpperIntervalCard x := by
          let O := {y : L // ¬x ≤ y}
          letI : Fintype O := Fintype.ofFinite _
          let f : Bool → O := fun b =>
            if b then
              ⟨cTop, hcTop.2⟩
            else
              ⟨⊥, fun h => hx_bot (le_antisymm h bot_le)⟩
          have hf : Function.Injective f := by
            intro a b hab
            cases a <;> cases b
            · rfl
            ·
              exfalso
              have hval := congrArg (fun z : O => z.1) hab
              simp [f] at hval
              exact hcTop.1 (hval.symm ▸ bot_le)
            ·
              exfalso
              have hval := congrArg (fun z : O => z.1) hab
              simp [f] at hval
              exact hcTop.1 (hval ▸ bot_le)
            · rfl
          have hcard := Fintype.card_le_of_injective f hf
          unfold outsideUpperIntervalCard
          simpa [O] using hcard
        have htotal := upperIntervalCard_add_outside x
        omega
      ·
        have hallInf :
            ∀ y : L, Incomparable y x → InfIrred y :=
          infIrred_of_incomparable_chain_and_greatest_not_supIrred
            hchain hcTop hgreat hcTopSup
        have hcBotInf : InfIrred cBot := hallInf cBot hcBot
        have hjInf : InfIrred j := hallInf j hjinc
        have hj_eq_bot :
            j = cBot :=
          minimumCounterexample_doublyIrred_unique hmin
            j cBot hj hjInf hcBotSup hcBotInf
        have hjqBot : upperIntervalCeil x cBot = q := by
          simpa [hj_eq_bot] using hjq
        have hconePartition :=
          upperConeCard_closure_add_incomparable
            hcBot hleast q hjqBot
        have houtside :=
          twice_incomparableCard_le_outsideUpperIntervalCard
            hchain hcBot hleast hcBotSup hallInf
            (minimumCounterexample_doublyIrred_unique hmin)
        have hbotExact :=
          minimumCounterexample_doublyIrred_upperCone
            hmin hcBotSup hcBotInf
        have htotal := upperIntervalCard_add_outside x
        omega
  have hminimal := hmin.2 (Set.Ici x) hinterval
  have hsmaller := card_upperInterval_lt x hx_bot
  omega

/--
UC-WP05-L014, Bouchard Corollary 2.14:
every non-endpoint element of a minimum counterexample is incomparable with at
least three elements.
-/
theorem minimumCounterexample_three_incomparables
    (hmin : IsMinimumCounterexample L)
    {x : L} (hx_bot : x ≠ ⊥) (hx_top : x ≠ ⊤) :
    3 ≤ (incomparableFinset x).card := by
  classical
  let P := incomparableFinset x
  have hPmem : ∀ y : L, y ∈ P ↔ Incomparable y x := by
    intro y
    exact mem_incomparableFinset
  have hnot_chain :
      ¬IsChain (· ≤ ·) (incomparableSet x) :=
    minimumCounterexample_incomparables_not_chain hmin hx_bot hx_top
  by_contra hlt
  change ¬3 ≤ P.card at hlt
  have hle_two : P.card ≤ 2 := by
    omega
  by_cases hle_one : P.card ≤ 1
  · have hsub : (incomparableSet x).Subsingleton := by
      intro a ha b hb
      exact
        Finset.card_le_one_iff.mp hle_one
          ((hPmem a).2 ha) ((hPmem b).2 hb)
    exact hnot_chain (hsub.isChain)
  have hcard_two : P.card = 2 := by
    omega
  obtain ⟨a, b, hab_ne, hpair⟩ := Finset.card_eq_two.mp hcard_two
  have haP : a ∈ P := by
    rw [hpair]
    simp
  have hbP : b ∈ P := by
    rw [hpair]
    simp
  have haInc : Incomparable a x := (hPmem a).1 haP
  have hbInc : Incomparable b x := (hPmem b).1 hbP
  have hset_pair : incomparableSet x = ({a, b} : Set L) := by
    ext y
    simp [incomparableSet, ← hPmem y, hpair]
  by_cases hab : a ≤ b
  · have hchain_pair : IsChain (· ≤ ·) ({a, b} : Set L) :=
      IsChain.pair hab
    exact hnot_chain (by simpa [hset_pair] using hchain_pair)
  by_cases hba : b ≤ a
  · have hchain_pair : IsChain (· ≤ ·) ({a, b} : Set L) := by
      simpa [Set.pair_comm] using (IsChain.pair hba :
        IsChain (· ≤ ·) ({b, a} : Set L))
    exact hnot_chain (by simpa [hset_pair] using hchain_pair)
  have haMax : Maximal (fun y => Incomparable y x) a := by
    refine ⟨haInc, ?_⟩
    intro y hy hay
    have hyP : y ∈ P := (hPmem y).2 hy
    have hya : y = a ∨ y = b := by
      simpa [hpair] using hyP
    rcases hya with rfl | rfl
    · exact le_rfl
    · exact (hab hay).elim
  have haMin : Minimal (fun y => Incomparable y x) a := by
    refine ⟨haInc, ?_⟩
    intro y hy hya
    have hyP : y ∈ P := (hPmem y).2 hy
    have hya' : y = a ∨ y = b := by
      simpa [hpair] using hyP
    rcases hya' with rfl | rfl
    · exact le_rfl
    · exact (hba hya).elim
  have hbMax : Maximal (fun y => Incomparable y x) b := by
    refine ⟨hbInc, ?_⟩
    intro y hy hby
    have hyP : y ∈ P := (hPmem y).2 hy
    have hyb : y = a ∨ y = b := by
      simpa [hpair] using hyP
    rcases hyb with rfl | rfl
    · exact (hba hby).elim
    · exact le_rfl
  have hbMin : Minimal (fun y => Incomparable y x) b := by
    refine ⟨hbInc, ?_⟩
    intro y hy hyb
    have hyP : y ∈ P := (hPmem y).2 hy
    have hyb' : y = a ∨ y = b := by
      simpa [hpair] using hyP
    rcases hyb' with rfl | rfl
    · exact (hab hyb).elim
    · exact le_rfl
  have haSup : SupIrred a := supIrred_of_minimal_incomparable haMin
  have haInf : InfIrred a := infIrred_of_maximal_incomparable haMax
  have hbSup : SupIrred b := supIrred_of_minimal_incomparable hbMin
  have hbInf : InfIrred b := infIrred_of_maximal_incomparable hbMax
  exact hab_ne
    (minimumCounterexample_doublyIrred_unique hmin
      a b haSup haInf hbSup hbInf)

/--
UC-WP05-L016, Bouchard Theorem 2.15(i) transfer:
an embedded finite lattice subposet of a minimum counterexample must touch the
ambient boundary if it contains two distinct internally doubly irreducible
elements.

The finite enumeration proving that every lattice of size `4..7` has such a
pair is replay-certified separately as `UC-WP05-C016`; this Lean theorem is the
checked no-boundary transfer step that turns that certificate into the branch
(i) contradiction.
-/
theorem minimumCounterexample_embeddedSubposet_twoDoublyIrred_boundary
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (hmin : IsMinimumCounterexample L)
    (e : K ↪o L)
    {x y : K} (hxy : x ≠ y)
    (hxSup : SupIrred x) (hxInf : InfIrred x)
    (hySup : SupIrred y) (hyInf : InfIrred y) :
    EmbeddedSubposet.HasBoundaryTouch e := by
  classical
  by_contra hno
  have hx_bot : x ≠ ⊥ := by
    intro h
    exact hxSup.not_isMin (by simpa [h] using isMin_bot)
  have hx_top : x ≠ ⊤ := by
    intro h
    exact hxInf.1 (by simpa [h] using isMax_top)
  have hy_bot : y ≠ ⊥ := by
    intro h
    exact hySup.not_isMin (by simpa [h] using isMin_bot)
  have hy_top : y ≠ ⊤ := by
    intro h
    exact hyInf.1 (by simpa [h] using isMax_top)
  have hxSupAmbient : SupIrred (e x) :=
    EmbeddedSubposet.ambient_supIrred_of_noBoundary hno hxSup hx_top
  have hxInfAmbient : InfIrred (e x) :=
    EmbeddedSubposet.ambient_infIrred_of_noBoundary hno hxInf hx_bot
  have hySupAmbient : SupIrred (e y) :=
    EmbeddedSubposet.ambient_supIrred_of_noBoundary hno hySup hy_top
  have hyInfAmbient : InfIrred (e y) :=
    EmbeddedSubposet.ambient_infIrred_of_noBoundary hno hyInf hy_bot
  have hxy_image :
      e x = e y :=
    minimumCounterexample_doublyIrred_unique hmin
      (e x) (e y) hxSupAmbient hxInfAmbient hySupAmbient hyInfAmbient
  exact hxy (e.injective hxy_image)

/--
UC-WP05-L015A, Bouchard Theorem 2.15(ii), join-reducible-top branch:
an embedded finite lattice subposet satisfying the dual-atom cardinality gap
must have a non-endpoint ambient boundary touch when its internal top is not
sup-irreducible.

The cardinality hypothesis `Fintype.card K + 2 < Fintype.card L` is the
subtraction-free Lean form of `|K| < |L| - 2`.
-/
theorem minimumCounterexample_embeddedSubposet_branchII_joinReducible_boundary
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (hmin : IsMinimumCounterexample L)
    (e : K ↪o L)
    (hK_nontrivial_gap : 2 < Fintype.card K)
    (hcard_gap : Fintype.card K + 2 < Fintype.card L)
    {d : L} (hd : IsCoatom d) (hdle : d ≤ e (⊤ : K))
    (hTop_not_sup : ¬SupIrred (⊤ : K)) :
    EmbeddedSubposet.HasBoundaryTouch e := by
  classical
  by_contra hno
  have hK_counter : IsCounterexample K := by
    constructor
    · omega
    · intro q hq
      have hq_top : q ≠ ⊤ := by
        intro hqtop
        exact hTop_not_sup (by simpa [hqtop] using hq)
      have hq_bot : q ≠ ⊥ := by
        intro hqbot
        exact hq.not_isMin (by simpa [hqbot] using isMin_bot)
      have hq_ambient :
          SupIrred (e q) :=
        EmbeddedSubposet.ambient_supIrred_of_noBoundary hno hq hq_top
      have hcounter := hmin.1.2 (e q) hq_ambient
      have hcone :
          upperConeCard (e q) ≤ upperConeCard q + 1 :=
        upperConeCard_embedded_add_one e hno hd hdle hq_bot hq_top
      omega
  have hminimal := hmin.2 K hK_counter
  omega

/--
The join-irreducible-top branch of Bouchard Theorem 2.15(ii): delete the
internal top of the embedded subposet and run the same minimality
contradiction, with two possible upper-cone points lost.
-/
theorem minimumCounterexample_embeddedSubposet_branchII_topIrred_boundary
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (hmin : IsMinimumCounterexample L)
    (e : K ↪o L)
    (hK_nontrivial_gap : 2 < Fintype.card K)
    (hcard_gap : Fintype.card K + 2 < Fintype.card L)
    {d : L} (hd : IsCoatom d) (hdle : d ≤ e (⊤ : K))
    (hTopSup : SupIrred (⊤ : K)) :
    EmbeddedSubposet.HasBoundaryTouch e := by
  classical
  by_contra hno
  letI : Lattice (Deleted (⊤ : K)) := deletedSupIrredLattice hTopSup
  letI : Fintype (Deleted (⊤ : K)) := Fintype.ofFinite _
  letI : Nonempty (Deleted (⊤ : K)) := ⟨⟨⊥, hTopSup.ne_bot.symm⟩⟩
  letI : BoundedOrder (Deleted (⊤ : K)) := Fintype.toBoundedOrder _
  have hcard_deleted :
      Fintype.card (Deleted (⊤ : K)) = Fintype.card K - 1 := by
    simp only [Fintype.card_subtype_compl, Fintype.card_subtype_eq]
  have hdeleted_counter : IsCounterexample (Deleted (⊤ : K)) := by
    constructor
    · rw [hcard_deleted]
      omega
    · intro q hq
      have hqKsup : SupIrred q.1 :=
        deletedTop_supIrred_to_original hTopSup q hq
      have hq_ambient :
          SupIrred (e q.1) :=
        EmbeddedSubposet.ambient_supIrred_of_noBoundary
          hno hqKsup q.2
      have hcounter := hmin.1.2 (e q.1) hq_ambient
      have hcone :
          upperConeCard (e q.1) ≤ upperConeCard q + 2 :=
        upperConeCard_embedded_deletedTop_add_two
          e hTopSup hno hd hdle q hqKsup.ne_bot
      rw [hcard_deleted]
      omega
  have hminimal := hmin.2 (Deleted (⊤ : K)) hdeleted_counter
  have hsmaller :
      Fintype.card (Deleted (⊤ : K)) < Fintype.card L := by
    rw [hcard_deleted]
    omega
  exact (not_le_of_gt hsmaller) hminimal

/--
UC-WP05-L015, Bouchard Theorem 2.15(ii): an embedded finite lattice subposet
of a minimum counterexample satisfying the dual-atom cardinality-gap criterion
must have a non-endpoint element that covers or is covered by an element
outside the embedded carrier.

This is the branch (ii) statement only. The branch (i) enumeration dependency
is replay-certified separately as `UC-WP05-C016` and linked to the ambient
boundary conclusion by
`minimumCounterexample_embeddedSubposet_twoDoublyIrred_boundary`.
-/
theorem minimumCounterexample_embeddedSubposet_branchII_boundary
    {K : Type u} [Fintype K] [Lattice K] [BoundedOrder K]
    (hmin : IsMinimumCounterexample L)
    (e : K ↪o L)
    (hK_nontrivial_gap : 2 < Fintype.card K)
    (hcard_gap : Fintype.card K + 2 < Fintype.card L)
    {d : L} (hd : IsCoatom d) (hdle : d ≤ e (⊤ : K)) :
    EmbeddedSubposet.HasBoundaryTouch e := by
  classical
  by_cases hTopSup : SupIrred (⊤ : K)
  · exact
      minimumCounterexample_embeddedSubposet_branchII_topIrred_boundary
        hmin e hK_nontrivial_gap hcard_gap hd hdle hTopSup
  · exact
      minimumCounterexample_embeddedSubposet_branchII_joinReducible_boundary
        hmin e hK_nontrivial_gap hcard_gap hd hdle hTopSup

end MathCert.UnionClosed.Lattice
