$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")
if (-not (Get-Command lake -ErrorAction SilentlyContinue)) { throw "lake is not installed; cannot certify Lean files." }
function Invoke-Control([string]$Path) { python $Path; if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE } }
lake build
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
lake build mathsolve/MathSolve
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
lake env lean MathCert/FormalSources/RHNSReplay.lean
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
lake env lean MathCert/FormalSources/UCRestrictedReplay.lean
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Invoke-Control "ci/validate_certification_routes.py"
Invoke-Control "ci/test_validate_certification_routes.py"
Invoke-Control "ci/validate_formal_source_provenance.py"
Invoke-Control "ci/test_formal_source_provenance.py"
Invoke-Control "ci/validate_formal_target_certificates.py"
Invoke-Control "ci/test_formal_target_certificates.py"
Invoke-Control "ci/validate_uc_restricted_qualification_schema.py"
Invoke-Control "ci/test_uc_restricted_qualification_schema.py"
Invoke-Control "ci/validate_uc_restricted_qualification.py"
Invoke-Control "ci/test_uc_restricted_qualification.py"
Invoke-Control "ci/validate_uc_provider_identity_exclusion.py"
Invoke-Control "ci/test_uc_provider_identity_exclusion.py"
Invoke-Control "ci/check_ledgers.py"
Invoke-Control "ci/test_validate_ledgers.py"
Invoke-Control "ci/validate_algebraic_certificates.py"
Invoke-Control "ci/test_validate_algebraic_certificates.py"
Invoke-Control "ci/validate_tropic_relu_certificates.py"
Invoke-Control "ci/test_validate_tropic_relu_certificates.py"
Invoke-Control "ci/test_validate_pb_certificate.py"
Invoke-Control "ci/replay_certificates.py"
Invoke-Control "ci/audit_certificate_coverage.py"
Invoke-Control "ci/test_audit_certificate_coverage.py"
Invoke-Control "ci/check_formal_trust.py"
Invoke-Control "ci/test_check_formal_trust.py"
Invoke-Control "ci/validate_openai_ten_proofs_result_family_intakes.py"
Invoke-Control "ci/test_openai_ten_proofs_result_family_intakes.py"
Invoke-Control "ci/validate_openai_ten_proofs_certification_work_packages.py"
Invoke-Control "ci/test_openai_ten_proofs_certification_work_packages.py"
Invoke-Control "ci/validate_openai_ten_proofs_replay_execution.py"
Invoke-Control "ci/test_openai_ten_proofs_replay_execution.py"
Invoke-Control "ci/validate_openai_ten_proofs_replay_evidence.py"
Invoke-Control "ci/test_openai_ten_proofs_replay_evidence.py"
Invoke-Control "ci/validate_openai_ten_proofs_route_proposals.py"
Invoke-Control "ci/test_openai_ten_proofs_route_proposals.py"
Invoke-Control "ci/validate_openai_ten_proofs_route_registrations.py"
Invoke-Control "ci/test_openai_ten_proofs_route_registrations.py"
Invoke-Control "ci/validate_human_steward_post_merge_attestation.py"
Invoke-Control "ci/test_human_steward_post_merge_attestation.py"
Invoke-Control "ci/validate_openai_ten_proofs_adjudication_design_with_successors.py"
Invoke-Control "ci/test_openai_ten_proofs_adjudication_contracts.py"
Invoke-Control "ci/validate_otp_ehrhart_adjudication.py"
Invoke-Control "ci/test_otp_ehrhart_adjudication.py"
Invoke-Control "ci/validate_otp_ehrhart_adjudication_post_merge_attestation.py"
Invoke-Control "ci/test_otp_ehrhart_adjudication_post_merge_attestation.py"
Invoke-Control "ci/validate_otp_ehrhart_output_candidate.py"
Invoke-Control "ci/test_otp_ehrhart_output_contract.py"
Invoke-Control "ci/test_otp_ehrhart_output_candidate.py"
Invoke-Control "ci/validate_otp_ehrhart_output_execution_post_merge_attestation.py"
Invoke-Control "ci/test_otp_ehrhart_output_execution_post_merge_attestation.py"
Invoke-Control "ci/audit_ci_reachability.py"
Invoke-Control "ci/test_audit_ci_reachability.py"
