#!/usr/bin/env bash
set -euo pipefail
if ! command -v lake >/dev/null 2>&1; then echo "lake is not installed; cannot certify Lean files." >&2; exit 1; fi
cd "$(dirname "$0")/.."
lake build
lake build mathsolve/MathSolve
lake env lean MathCert/FormalSources/RHNSReplay.lean
lake env lean MathCert/FormalSources/UCRestrictedReplay.lean
lake env lean MathCert/Domains/NumberTheory/EuclidGCD.lean
lake env lean MathCert/Domains/NumberTheory/EuclidDiophantine.lean
python3 ci/validate_certification_routes.py
python3 ci/test_validate_certification_routes.py
python3 ci/validate_formal_source_provenance.py
python3 ci/test_formal_source_provenance.py
python3 ci/validate_formal_target_certificates.py
python3 ci/test_formal_target_certificates.py
python3 ci/validate_uc_restricted_qualification_schema.py
python3 ci/test_uc_restricted_qualification_schema.py
python3 ci/validate_uc_restricted_qualification.py
python3 ci/test_uc_restricted_qualification.py
python3 ci/validate_uc_provider_identity_exclusion.py
python3 ci/test_uc_provider_identity_exclusion.py
python3 ci/check_ledgers.py
python3 ci/test_validate_ledgers.py
python3 ci/validate_algebraic_certificates.py
python3 ci/test_validate_algebraic_certificates.py
python3 ci/validate_tropic_relu_certificates.py
python3 ci/test_validate_tropic_relu_certificates.py
python3 ci/test_validate_pb_certificate.py
python3 ci/replay_certificates.py
python3 ci/audit_certificate_coverage.py
python3 ci/test_audit_certificate_coverage.py
python3 ci/check_formal_trust.py
python3 ci/test_check_formal_trust.py
python3 ci/validate_openai_ten_proofs_result_family_intakes.py
python3 ci/test_openai_ten_proofs_result_family_intakes.py
python3 ci/validate_openai_ten_proofs_certification_work_packages.py
python3 ci/test_openai_ten_proofs_certification_work_packages.py
python3 ci/validate_openai_ten_proofs_permanent_certification_work_package.py
python3 ci/test_openai_ten_proofs_permanent_certification_work_package.py
python3 ci/validate_openai_ten_proofs_replay_execution.py
python3 ci/test_openai_ten_proofs_replay_execution.py
python3 ci/validate_openai_ten_proofs_replay_evidence.py
python3 ci/test_openai_ten_proofs_replay_evidence.py
python3 ci/validate_openai_ten_proofs_permanent_cert_replay_evidence.py
python3 ci/test_openai_ten_proofs_permanent_cert_replay_evidence.py
python3 ci/validate_openai_ten_proofs_route_proposals.py
python3 ci/test_openai_ten_proofs_route_proposals.py
python3 ci/validate_openai_ten_proofs_route_registrations.py
python3 ci/test_openai_ten_proofs_route_registrations.py
python3 ci/validate_human_steward_post_merge_attestation.py
python3 ci/test_human_steward_post_merge_attestation.py
python3 ci/validate_openai_ten_proofs_adjudication_design_with_successors.py
python3 ci/test_openai_ten_proofs_adjudication_contracts.py
python3 ci/validate_otp_ehrhart_adjudication.py
python3 ci/test_otp_ehrhart_adjudication.py
python3 ci/validate_otp_ehrhart_adjudication_post_merge_attestation.py
python3 ci/test_otp_ehrhart_adjudication_post_merge_attestation.py
python3 ci/validate_otp_ehrhart_output_candidate.py
python3 ci/test_otp_ehrhart_output_contract.py
python3 ci/test_otp_ehrhart_output_candidate.py
python3 ci/validate_otp_ehrhart_output_execution_post_merge_attestation.py
python3 ci/test_otp_ehrhart_output_execution_post_merge_attestation.py
python3 ci/validate_otp_compactness_evidence_refresh.py
python3 ci/test_otp_compactness_evidence_refresh.py
python3 work_packages/EUCLID_GCD_E2E_001/check_certificate.py
python3 work_packages/EUCLID_GCD_E2E_001/test_certificate.py
python3 work_packages/EUCLID_DIOPHANTINE_E2E_002/check_certificate.py
python3 work_packages/EUCLID_DIOPHANTINE_E2E_002/test_certificate.py
python3 ci/validate_vgse_route_registration.py
python3 ci/test_vgse_route_registration.py
python3 ci/audit_ci_reachability.py
python3 ci/test_audit_ci_reachability.py
